#pragma once
#include "Units/Dire_units/Unit_adapter/Dire_archer_adapter.h"
#include "Units/Dire_units/Unit_adapter/Dire_horseman_adapter.h"
#include "Units/Dire_units/Unit_adapter/Dire_mage_adapter.h"
#include "Units/Dire_units/Unit_adapter/Dire_knight_adapter.h"
#include "Units/Radiant_Units/Unit_adapter/Radiant_archer_adapter.h"
#include "Units/Radiant_Units/Unit_adapter/Radiant_horseman_adapter.h"
#include "Units/Radiant_Units/Unit_adapter/Radiant_knight_adapter.h"
#include "Units/Radiant_Units/Unit_adapter/Radiant_mage_adapter.h"